/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":service"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.ibeetl:sql-core")
    implementation("cn.dev33:sa-token-spring-boot3-starter")

}
springBoot {
    mainClass.set("org.cv.Application")
}
/*application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}*/
